services:
  navigation:
    build: .
    image: navigation2-2026-envs:latest
    container_name: navigation2
    command: /bin/bash
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    stop_grace_period: &STOP_GRACE_PERIOD 1s

    # mount our navigation code
    volumes:
      - ~/Eurobot-2026-ws/Eurobot-2026-Navigation:/home/user/Eurobot-2026-Navigation # TODO: Check for working directories
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/user/.Xauthority
      - /dev:/dev

    working_dir:
      /home/user/Eurobot-2026-Navigation

    environment:
      - DISPLAY=${DISPLAY}  # Set display environment variable
      - RCUTILS_COLORIZED_OUTPUT=1
      - XAUTHORITY=/home/user/.Xauthority   # Set Xauthority path
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=50  # ! Please distinguish the domain ID with other containers
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia 
              count: all     
              capabilities: [gpu, utility, compute]
